### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Sudoku#56]
Progressen i sudokut sparas, detta gör att när man startar om sidan ser den direkt att man gjort klart sudokut och frågar användaren ifall den vill lägga till ett nytt resultat på topplistan. Tiden blir då 0.

**Comment by EdwardKN** [comment]
Jag har aldrig sett problemet tidigare och lyckas inte återskapa det.

**Comment by EndyMc** [comment]
En annan konstig sak är att mitt bräde verkade finnas på github.io sidan trots att jag löste den på en localhost sida

**Comment by EndyMc** [comment]
> Jag har aldrig sett problemet tidigare och lyckas inte återskapa det.

Testa i firefox

**Comment by EdwardKN** [comment]
vettefan om jag kan fixa
